package view.display;

import org.jhotdraw.undo.*;

import java.io.*;
import java.net.URI;


import org.jhotdraw.app.AbstractView;
import org.jhotdraw.draw.*;
import org.jhotdraw.gui.URIChooser;
import view.console.ConsolePanel;

/**
 * OpenCLPadDisplayView shows a DrawingView where users create and modify figures.
 *
 * @version 0.1beta
 * @since 8/12/13 5:05 PM
 * @author HongKee Moon
 */

public class OpenCLPadDisplayView extends AbstractView {

    /**
     * Each DrawView uses its own undo redo manager.
     * This allows for undoing and redoing actions per view.
     */
    private UndoRedoManager undo;

    /**
     * Depending on the type of an application, there may be one editor per
     * view, or a single shared editor for all views.
     */
    private DrawingEditor editor;

    /**
     * Creates a new view.
     */
    public OpenCLPadDisplayView() {

        try{
            initComponents();
        } catch (Exception ex)
        {
            ex.printStackTrace();
        }

        editor = new DefaultDrawingEditor();
    }

    /**
     * Initializes view specific actions.
     */
    private void initActions() {

    }

    @Override
    protected void setHasUnsavedChanges(boolean newValue) {
        super.setHasUnsavedChanges(newValue);
        undo.setHasSignificantEdits(newValue);
    }

    /**
     * Writes the view to the specified uri.
     */
    @Override
    public void write(URI f, URIChooser fc) throws IOException {

    }

    /**
     * Reads the view from the specified uri.
     */
    @Override
    public void read(URI f, URIChooser fc) throws IOException {
    }


    /**
     * Sets a drawing editor for the view.
     */
    public void setEditor(DrawingEditor newValue) {
    }


    /**
     * Clears the view.
     */
    @Override
    public void clear() {
    }

    @Override
    public boolean canSaveTo(URI file) {
        return new File(file).getName().endsWith(".xml");
    }



    @Override
    public boolean hasUnsavedChanges() {
        return false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        setLayout(new java.awt.BorderLayout());
        add(new ConsolePanel(), java.awt.BorderLayout.CENTER);
        this.setTitle("Console");
    }// </editor-fold>//GEN-END:initComponents
}

